version: '3'

networks:
  kafka-net:
    name: kafka-net
    external: true

services:
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    hostname: kafka-ui
    container_name: kafka-ui
    restart: always
    environment:
      TZ: Asia/Seoul
      KAFKA_CLUSTERS_0_NAME: kafka1
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zoo1:2181
      SERVER_SERVLET_CONTEXT_PATH: /kafka-ui
    ports:
      - "127.0.0.1:9101:8080"
    networks:
      kafka-net:
        ipv4_address: 192.168.40.51
