version: '3'

services:
  zookeeper1:
    image: bitnami/zookeeper
    hostname: zookeeper1
    container_name: zookeeper1
    user: root
    volumes:
      - ~/data/zookeeper1:/bitnami/zookeeper
    environment:
      - ZOO_SERVER_ID=1
      - ZOO_SERVERS=0.0.0.0:2888:3888,zookeeper2:2888:3888,zookeeper3:2888:3888
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_ENABLE_PROMETHEUS_METRICS=yes
    networks:
      - default

  zookeeper2:
    image: bitnami/zookeeper
    hostname: zookeeper2
    container_name: zookeeper2
    user: root
    volumes:
      - ~/data/zookeeper2:/bitnami/zookeeper
    environment:
      - ZOO_SERVER_ID=2
      - ZOO_SERVERS=zookeeper1:2888:3888,0.0.0.0:2888:3888,zookeeper3:2888:3888
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_ENABLE_PROMETHEUS_METRICS=yes
    networks:
      - default

  zookeeper3:
    image: bitnami/zookeeper
    hostname: zookeeper3
    container_name: zookeeper3
    user: root
    volumes:
      - ~/data/zookeeper3:/bitnami/zookeeper
    environment:
      - ZOO_SERVER_ID=3
      - ZOO_SERVERS=zookeeper1:2888:3888,zookeeper2:2888:3888,0.0.0.0:2888:3888
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_ENABLE_PROMETHEUS_METRICS=yes
    networks:
      - default

