version: '3'

services:
    nginx:
        image: nginx:1.15-alpine
        container_name: nginx
        volumes: 
            - "../configs/nginx/nginx.conf:/etc/nginx/nginx.conf"
        environment:
            - TZ=Asia/Seoul
        ports:
            - 80:80
            - 443:443
            - 4100:4100
