version: '3'

services:
  redis-ui:
    hostname: redis-ui
    container_name: redis-ui
    image: patrikx3/p3x-redis-ui:latest
    ports:
      - 7843:7843
    volumes:
      - /home/jib/data/redis-ui-settings:/settings
