version: '3'

networks:
  kafka-net:
    name: kafka-net
    external: true

services:
  kafka1:
    image: bitnami/kafka:3.1.2
    hostname: kafka1
    container_name: kafka1
    restart: always
    environment:
      - TZ=Asia/Seoul
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zoo1:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka1:9092,EXTERNAL://192.168.40.101:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zoo1
    volumes:
      - ~/data/kafka1:/bitnami/kafka
    ports:
      - "9093:9092"
    networks:
      kafka-net:
        ipv4_address: 192.168.40.101

  zoo1:
    image: bitnami/zookeeper:3.5.10
    hostname: zoo1
    container_name: zoo1
    restart: always
    environment:
      - TZ=Asia/Seoul
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - ~/data/zoo1:/bitnami/zookeeper
    networks:
      kafka-net:
        ipv4_address: 192.168.40.11