version: '3'

networks:
  kafka-net:
    name: kafka-net
    external: true

services:
  kafka1:
    image: bitnami/kafka:3.1.2
    hostname: kafka1
    container_name: kafka1
    restart: always
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CLIENT_USERS=ibjang
      - KAFKA_CLIENT_PASSWORDS=ibjang123
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zoo1:2181,zoo2:2181,zoo3:2181
      # - KAFKA_INTER_BROKER_USER=kafka
      # - KAFKA_INTER_BROKER_PASSWORD=kafka111
      # - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      # - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:SASL_PLAINTEXT,CLIENT:SASL_PLAINTEXT
      # - KAFKA_CFG_LISTENERS=INTERNAL://:9092,CLIENT://:9093,
      # - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://192.168.30.101:9092,CLIENT://192.168.30.101:9093
      # - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=SASL_PLAINTEXT
      # - KAFKA_CFG_SASL_ENABLED_MECHANISMS=SASL_PLAINTEXT
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CLIENT:SASL_PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,CLIENT://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka1:9092,CLIENT://192.168.30.101:9093
      - KAFKA_ZOOKEEPER_PROTOCOL=SASL
      - KAFKA_ZOOKEEPER_USER=zkserverid
      - KAFKA_ZOOKEEPER_PASSWORD=zkserverpw
      - TZ=Asia/Seoul
    # volumes:
      # - ~/data/kafka1:/bitnami/kafka
    ports:
      - "9092:9093"
    networks:
      kafka-net:
        ipv4_address: 192.168.30.101

  kafka2:
    image: bitnami/kafka:3.1.2
    hostname: kafka2
    container_name: kafka2
    restart: always
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_CLIENT_USERS=ibjang
      - KAFKA_CLIENT_PASSWORDS=ibjang123
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zoo1:2181,zoo2:2181,zoo3:2181
      # - KAFKA_INTER_BROKER_USER=kafka
      # - KAFKA_INTER_BROKER_PASSWORD=kafka111
      # - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      # - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:SASL_PLAINTEXT,CLIENT:SASL_PLAINTEXT
      # - KAFKA_CFG_LISTENERS=INTERNAL://:9092,CLIENT://:9093,
      # - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://192.168.30.102:9092,CLIENT://192.168.30.102:9093
      # - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=SASL_PLAINTEXT
      # - KAFKA_CFG_SASL_ENABLED_MECHANISMS=SASL_PLAINTEXT
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CLIENT:SASL_PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,CLIENT://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka2:9092,CLIENT://192.168.30.102:9093
      - KAFKA_ZOOKEEPER_PROTOCOL=SASL
      - KAFKA_ZOOKEEPER_USER=zkserverid
      - KAFKA_ZOOKEEPER_PASSWORD=zkserverpw
      - TZ=Asia/Seoul
    # volumes:
      # - ~/data/kafka2:/bitnami/kafka
    ports:
      - "9093:9093"
    networks:
      kafka-net:
        ipv4_address: 192.168.30.102

  kafka3:
    image: bitnami/kafka:3.1.2
    hostname: kafka3
    container_name: kafka3
    restart: always
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_CLIENT_USERS=ibjang
      - KAFKA_CLIENT_PASSWORDS=ibjang123
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zoo1:2181,zoo2:2181,zoo3:2181
      # - KAFKA_INTER_BROKER_USER=kafka
      # - KAFKA_INTER_BROKER_PASSWORD=kafka111
      # - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      # - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:SASL_PLAINTEXT,CLIENT:SASL_PLAINTEXT
      # - KAFKA_CFG_LISTENERS=INTERNAL://:9092,CLIENT://:9093,
      # - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://192.168.30.103:9092,CLIENT://192.168.30.103:9093
      # - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=SASL_PLAINTEXT
      # - KAFKA_CFG_SASL_ENABLED_MECHANISMS=SASL_PLAINTEXT
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CLIENT:SASL_PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,CLIENT://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka3:9092,CLIENT://192.168.30.103:9093
      - KAFKA_ZOOKEEPER_PROTOCOL=SASL
      - KAFKA_ZOOKEEPER_USER=zkserverid
      - KAFKA_ZOOKEEPER_PASSWORD=zkserverpw
      - TZ=Asia/Seoul
    # volumes:
      # - ~/data/kafka3:/bitnami/kafka
    ports:
      - "9094:9093"
    networks:
      kafka-net:
        ipv4_address: 192.168.30.103