version: '3'

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/16
          gateway: 192.168.0.1
  zookeeper_default:
    name: zookeeper_default
    external: true

services:
  kafka-broker1:
    image: bitnami/kafka
    hostname: kafka-broker1
    container_name: kafka-broker1
    restart: always
    user: root
    volumes:
      - ~/data/kafka-broker1:/bitnami/kafka
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.30.101:9092
    ports:
      - "9092:9092"
    networks:
      default:
        ipv4_address: 192.168.30.101
      zookeeper_default:

  kafka-broker2:
    image: bitnami/kafka
    hostname: kafka-broker2
    container_name: kafka-broker2
    restart: always
    user: root
    volumes:
      - ~/data/kafka-broker2:/bitnami/kafka
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.30.102:9092
    ports:
      - "9093:9092"
    networks:
      default:
        ipv4_address: 192.168.30.102
      zookeeper_default:

  kafka-broker3:
    image: bitnami/kafka
    hostname: kafka-broker3
    container_name: kafka-broker3
    restart: always
    user: root
    volumes:
      - ~/data/kafka-broker3:/bitnami/kafka
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.30.103:9092
    ports:
      - "9094:9092"
    networks:
      default:
        ipv4_address: 192.168.30.103
      zookeeper_default:
