version: '3'

networks:
  zookeeper_default:
    name: zookeeper_default
    external: true

services:
  kafka-broker1:
    image: bitnami/kafka
    hostname: kafka-broker1
    container_name: kafka-broker1
    user: root
    volumes:
      - ~/data/kafka-broker1:/bitnami/kafka
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"
    networks:
      - default
      - zookeeper_default

  kafka-broker2:
    image: bitnami/kafka
    hostname: kafka-broker2
    container_name: kafka-broker2
    user: root
    volumes:
      - ~/data/kafka-broker2:/bitnami/kafka
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9093:9092"
    networks:
      - default
      - zookeeper_default

  kafka-broker3:
    image: bitnami/kafka
    hostname: kafka-broker3
    container_name: kafka-broker3
    user: root
    volumes:
      - ~/data/kafka-broker3:/bitnami/kafka
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9094:9092"
    networks:
      - default
      - zookeeper_default
